# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name : DevOpsAgent

variables:
dockerRegistryServiceConnection: 'YOUR-DOCKER-CONNECTION'
frontendImageName: 'frontend'
backendImageName: 'backend'
tag: '$(Build.BuildId)'
 
stages:
- stage: Build
jobs:
- job: Build_Frontend
displayName: Build Frontend Image
 
steps:
- checkout: self

- task: Docker@2
displayName: Build Frontend Docker Image
inputs:
command: build
repository: $(frontendImageName)
Dockerfile: frontend/Dockerfile
buildContext: frontend
tags: |
$(tag)
 
- job: Build_Backend
displayName: Build Backend Image
 
steps:
- checkout: self
 
- task: Docker@2
displayName: Build Backend Docker Image
inputs:
command: build
repository: $(backendImageName)
Dockerfile: backend/Dockerfile
buildContext: backend
tags: |
$(tag) 